language: scala
scala:
  - 2.9.2
jdk:
  - oraclejdk7
install: /bin/true # always succeeds
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn -B clean test
