language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
install: /bin/true # always succeeds
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn -e -B test -Ptravis
